name: Build Eleventy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5

      - name: Install lilypond
        run: |
          sudo apt update
          sudo apt install lilypond

      - name: Use Node.js 20
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install dependencies & build
        timeout-minutes: 10
        run: |
          npm ci
          npm run build:ci

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./public
          github_token: ${{ secrets.GITHUB_TOKEN }}
